import type { Metadata } from "next";
import { Fragment, use } from "react";
import type { APIReference, Graph, SoftwareSourceCode, TechArticle } from "schema-dts";
import { PapyrusScriptFunctionIndexedAggregate, type PapyrusScriptEventOrBaseFunctionIndexedAggregate } from "../../../../../../../papyrus/data-structures/indexing/function";
import { AllSourcesCombined, type PapyrusGameDataIndexed } from "../../../../../../../papyrus/data-structures/indexing/game";
import type { PapyrusGame } from "../../../../../../../papyrus/data-structures/pure/game";
import { AllScriptsIndexed } from "../../../../../../../papyrus/indexing/index-all";
import { prepareUrlPart, prepareUrlParts } from "../../../../../../../utils/prepareUrlParts";
import { getBestStringVariant } from "../../../../../../../utils/getBestName";
import { getGameName } from "../../../../../../../utils/getGameName";
import { toLowerCase } from "../../../../../../../utils/toLowerCase";
import { CodeBlock, CodeBlockLanguage } from "../../../../../../components/code-block/CodeBlock";
import { GuardEmptyList } from "../../../../../../components/GuardEmptyList";
import { JsonLDGraph } from "../../../../../../components/JsonLDGraph";
import { SourceName } from "../../../../../../components/papyrus/SourceName";
import { PapyrusTypeNamed, PapyrusTypeWithValue } from "../../../../../../components/papyrus/type/PapyrusType";
import { SuspenseIfDevelopment } from "../../../../../../components/SuspenseIfDevelopment";
import { TextWithTooltip } from "../../../../../../components/text-with-tooltip/TooltipText";
import { AUTOMATIC_BASE_URL, WikiMarkdown } from "../../../../../../components/wiki-markdown/WikiMarkdown";
import styles from './EventPage.module.scss';
import { getGameAndScriptAndEventFromParams, type EventRouteParams } from "./getGameAndScriptAndEventFromParams";
import { sourcesSortFn } from "../../../../../../components/papyrus/SourcesList";
import { EventDocumentationStringRaw } from "@/app/components/papyrus/event/signature/DocumentationString";
import { getMediaWikiEventData } from "@/wiki-data-extraction/ck-wiki/data-extraction/getMediaWikiEventData";
import { PapyrusEventSignatureVariants } from "@/app/components/papyrus/event/signature/EventSignatureVariants";
import { getGitHubWikiEventData } from "@/app/components/papyrus/event/signature/getGitHubWikiEventDescription";
import { AutoGeneratedEventExampleText } from "@/app/components/papyrus/event/AutoGeneratedEventExampleText";
import { PapyrusScriptFunctionReference } from "@/app/components/papyrus/function/reference/PapyrusScriptFunctionReference";
import { NotFoundChip } from "@/app/components/NotFoundChip";

export function generateStaticParams(): EventRouteParams[] {
    const params: EventRouteParams[] = [];
    for (const [game, gameData] of Object.entries(AllScriptsIndexed)) {
        for (const [scriptNameLowercase, scriptData] of Object.entries(gameData.scripts)) {
            for (const evtName of Object.keys(scriptData[AllSourcesCombined].events))
                params.push({game: prepareUrlPart(game), scriptNameNoExt: prepareUrlPart(scriptNameLowercase), eventName: prepareUrlPart(evtName)});
        }
    }

    return params;
}

export async function generateMetadata({params}: {readonly params: Promise<EventRouteParams>}): Promise<Metadata> {
    const {game, scriptBySources, evt} = getGameAndScriptAndEventFromParams(await params);

    const sourceIDs = Object.keys(scriptBySources);
    const sourceNames = sourceIDs.map(sourceId => AllScriptsIndexed[game].scriptSources[sourceId]!).sort(sourcesSortFn).map((source)=>SourceName({source, long: true}));

    if (sourceNames.length === 0) throw new Error('A script should have at least one source! Makes no sense for it to not have a source! Something is VERY wrong here.');
    const sourcesList = sourceNames.length === 1 ? sourceNames[0] : sourceNames.length === 2 ? sourceNames.join(' and ') : `${sourceNames.slice(0, -1).join(', ')}, and ${sourceNames.at(-1)}`;

    const scriptNamespaceName = getBestStringVariant(scriptBySources[AllSourcesCombined].namespaceName)![1];
    const description = await EventDocumentationStringRaw({game, evt, scriptName: scriptNamespaceName});

    const eventName = getBestStringVariant(evt.name)![1];

    return {
        title: eventName,
        description: `Reference page for the event ${scriptNamespaceName}.${eventName} for the game ${getGameName(game)}. This event is provided by the ${scriptNamespaceName} script found in ${sourcesList}.${description ? `\n\n${description}` : ''}`,
        // TODO: Add keywords relevant to the event.
        // Possibly break its name down into parts, take its parameters into account, return type, parent script, and all that fun stuff.
    };
}

export default async function EventPage({params}: {readonly params: Promise<EventRouteParams>}) {
    const {game, scriptBySources, evt} = getGameAndScriptAndEventFromParams(await params);

    const scriptNamespaceName = getBestStringVariant(scriptBySources[AllSourcesCombined].namespaceName)![1];

    const ckWikiDataPromise = getMediaWikiEventData(game, evt, scriptNamespaceName);
    const githubWikiDataPromise = Promise.resolve(getGitHubWikiEventData(evt));

    return <>
        <main>
            <GuardEmptyList replacement={<p>No variants of this event found.</p>}>
                <PapyrusEventSignatureVariants game={game} evtAggregate={evt} scriptName={scriptNamespaceName} longerDescription />
            </GuardEmptyList>


            <SuspenseIfDevelopment fallback={<p>[Development] Loading caveats...</p>}>
                <RegistrationFunctions evt={evt} githubWikiDataPromise={githubWikiDataPromise} />
            </SuspenseIfDevelopment>

            <SuspenseIfDevelopment fallback={<p>[Development] Loading caveats...</p>}>
                <Caveats
                    evt={evt}
                    ckWikiDataPromise={ckWikiDataPromise} githubWikiDataPromise={githubWikiDataPromise}
                />
            </SuspenseIfDevelopment>

            <SuspenseIfDevelopment fallback={<p>[Development] Loading parameters...</p>}>
                <Parameters
                    evt={evt}
                    ckWikiDataPromise={ckWikiDataPromise} githubWikiDataPromise={githubWikiDataPromise}
                />
            </SuspenseIfDevelopment>

            <SuspenseIfDevelopment fallback={<p>[Development] Loading examples...</p>}>
                <Examples
                    evt={evt} scriptNamespaceName={scriptNamespaceName}
                    ckWikiDataPromise={ckWikiDataPromise} githubWikiDataPromise={githubWikiDataPromise}
                />
            </SuspenseIfDevelopment>

            <SuspenseIfDevelopment fallback={<p>[Development] Loading related pages...</p>}>
                <RelatedPages
                    gameData={evt.game}
                    ckWikiDataPromise={ckWikiDataPromise}
                    githubWikiDataPromise={githubWikiDataPromise}
                />
            </SuspenseIfDevelopment>

            <SuspenseIfDevelopment fallback={<p>[Development] Loading wiki link...</p>}>
                <AdditionalReferences
                    game={game}
                    ckWikiDataPromise={ckWikiDataPromise} githubWikiDataPromise={githubWikiDataPromise}
                />
            </SuspenseIfDevelopment>
        </main>
        <SuspenseIfDevelopment fallback={null}>
            {(async (): Promise<Graph['@graph']> => {
                const metadata = await generateMetadata({params});
                const ckWikiData = await ckWikiDataPromise;
                const githubWikiData = await githubWikiDataPromise;
                return [
                    {
                        "@type": "APIReference",
                        "@id": `https://papyrus.bellcube.dev${prepareUrlParts(game, 'script', scriptBySources[AllSourcesCombined].namespaceName[0]![1], 'event', evt.name[0]![1])}#event`,
                        url: `https://papyrus.bellcube.dev${prepareUrlParts(game, 'script', scriptBySources[AllSourcesCombined].namespaceName[0]![1], 'event', evt.name[0]![1])}`,
                        mainEntityOfPage: { "@id": `https://papyrus.bellcube.dev${prepareUrlParts(game, 'script', scriptBySources[AllSourcesCombined].namespaceName[0]![1], 'event', evt.name[0]![1])}#event` },
                        isPartOf: { "@id": `https://papyrus.bellcube.dev${prepareUrlParts(game, 'script', scriptBySources[AllSourcesCombined].namespaceName[0]![1])}#script` },
                        about: { "@id": `https://papyrus.bellcube.dev${prepareUrlParts(game, 'script', scriptBySources[AllSourcesCombined].namespaceName[0]![1], 'event', evt.name[0]![1])}#code` },
                        name: getBestStringVariant(evt.name)![1],
                        description: metadata.description!,
                        isBasedOn: [
                            ...(!ckWikiData ? [] : [{
                                "@type": "TechArticle",
                                url: ckWikiData?.wikiPageUrl,
                            } satisfies TechArticle]) as unknown as TechArticle[],
                            ...githubWikiData.map(([_wikiIdentifier, wikiData]) => ({
                                "@type": "TechArticle",
                                url: wikiData.linkToWikiData,
                            } satisfies TechArticle)) as unknown as TechArticle[],
                        ] satisfies TechArticle[],
                    } satisfies APIReference,
                    {
                        "@type": "SoftwareSourceCode",
                        "@id": `https://papyrus.bellcube.dev${prepareUrlParts(game, 'script', scriptBySources[AllSourcesCombined].namespaceName[0]![1], 'event', evt.name[0]![1])}#code`,
                        url: `https://papyrus.bellcube.dev${prepareUrlParts(game, 'script', scriptBySources[AllSourcesCombined].namespaceName[0]![1], 'event', evt.name[0]![1])}`,
                        mainEntityOfPage: { "@id": `https://papyrus.bellcube.dev${prepareUrlParts(game, 'script', scriptBySources[AllSourcesCombined].namespaceName[0]![1], 'event', evt.name[0]![1])}#event` },
                        isPartOf: { "@id": `https://papyrus.bellcube.dev${prepareUrlParts(game, 'script', scriptBySources[AllSourcesCombined].namespaceName[0]![1])}#script` },
                        programmingLanguage: "Papyrus",
                        codeSampleType: "event",
                        name: getBestStringVariant(evt.name)![1],
                        description: await EventDocumentationStringRaw({game, evt, scriptName: scriptNamespaceName}),
                    } satisfies SoftwareSourceCode,
                    {
                        "@type": "BreadcrumbList",
                        "@id": `https://papyrus.bellcube.dev${prepareUrlParts(game, 'script', scriptBySources[AllSourcesCombined].namespaceName[0]![1], 'event', evt.name[0]![1])}#breadcrumb`,
                        itemListElement: [
                            {
                                "@type": "ListItem",
                                position: 1,
                                name: "Home",
                                item: "https://papyrus.bellcube.dev/",
                            },
                            {
                                "@type": "ListItem",
                                position: 2,
                                name: getGameName(game),
                                item: `https://papyrus.bellcube.dev${prepareUrlParts(game)}`,
                            },
                            {
                                "@type": "ListItem",
                                position: 3,
                                name: scriptNamespaceName,
                                item: `https://papyrus.bellcube.dev${prepareUrlParts(game, 'script', scriptBySources[AllSourcesCombined].namespaceName[0]![1])}`,
                            },
                            {
                                "@type": "ListItem",
                                position: 4,
                                name: getBestStringVariant(evt.name)![1],
                                item: `https://papyrus.bellcube.dev${prepareUrlParts(game, 'script', scriptBySources[AllSourcesCombined].namespaceName[0]![1], 'event', evt.name[0]![1])}`,
                            },
                        ],
                    },
                ];
            })().then((data) => <JsonLDGraph data={data} />)}
        </SuspenseIfDevelopment>
    </>;
}

function Examples({evt, ckWikiDataPromise, githubWikiDataPromise, scriptNamespaceName}: {readonly scriptNamespaceName: string, readonly evt: PapyrusScriptEventOrBaseFunctionIndexedAggregate<PapyrusGame>, readonly ckWikiDataPromise: ReturnType<typeof getMediaWikiEventData>, readonly githubWikiDataPromise: Promise<Awaited<ReturnType<typeof getGitHubWikiEventData>>>}) {
    const ckWikiData = use(ckWikiDataPromise);
    const githubWikiData = use(githubWikiDataPromise);
    return <>
        <br />
        <h2>Examples</h2>
        {/* eslint-disable-next-line react/no-unstable-nested-components -- these components are server components, so we don't really care */}
        <GuardEmptyList replacement={<p>No human-generated examples found for this event.</p>} Wrapper={({children}) =>
            <div data-analytics-id="docs-examples">
                {children}
            </div>}
        >
            {ckWikiData?.examplesData.map((example) =>
                <div key={example.code}>
                    <CodeBlock language={CodeBlockLanguage.Papyrus} code={example.code} />
                </div>
            )}
            {githubWikiData?.filter(([,wikiData])=>wikiData.exampleMDs.length > 0).flatMap(([_sourceIdentifier, wikiData]) =>
                wikiData.exampleMDs.map((exampleMd) =>
                    <div key={exampleMd}>
                        <WikiMarkdown data-analytics-id="docs-examples-githubwiki" gameData={evt.game}
                            md={exampleMd} baseURL={wikiData.linkToWikiData} />
                    </div>
                )
            )}
        </GuardEmptyList>

        <h3>
            <TextWithTooltip tooltipContents={<>
                <p>This example is auto-generated to show new Papyrus programmers roughly how to use this event.</p>
                <p>This example is NOT meant to be practical, nor is it meant to demonstrate anything more than the basic syntax of the event.</p>
            </>}>
                Auto-Generated Example
            </TextWithTooltip>
        </h3>
        <CodeBlock language={CodeBlockLanguage.Papyrus} code={AutoGeneratedEventExampleText({evt: Object.values(evt.$sources)[0]!, scriptName: scriptNamespaceName, registrationControls: null})} />
    </>;
}

function Caveats({evt, ckWikiDataPromise, githubWikiDataPromise}: {readonly evt: PapyrusScriptEventOrBaseFunctionIndexedAggregate<PapyrusGame>, readonly ckWikiDataPromise: ReturnType<typeof getMediaWikiEventData>, readonly githubWikiDataPromise: Promise<Awaited<ReturnType<typeof getGitHubWikiEventData>>>}) {
    const ckWikiData = use(ckWikiDataPromise);
    const githubWikiData = use(githubWikiDataPromise);


    // eslint-disable-next-line react/no-unstable-nested-components -- these components are server components, so we don't really care
    return <GuardEmptyList replacement={null} Wrapper={({children}) => <>
        <br />
        <div data-analytics-id="docs-caveats">
            <h2>Caveats</h2>
            {children}
        </div>
    </>}>
        {ckWikiData?.notesMarkdown ? <>
            <h3>CK Wiki - Notes</h3>
            <WikiMarkdown data-analytics-id="docs-notes-ckwiki" gameData={evt.game} md={ckWikiData.notesMarkdown} baseURL={ckWikiData.wikiPageUrl} />
        </>: []}
        {ckWikiData?.bugsMarkdown ? <>
            <h3>CK Wiki - Known Bugs</h3>
            <WikiMarkdown data-analytics-id="docs-notes-ckwiki" gameData={evt.game} md={ckWikiData.bugsMarkdown} baseURL={ckWikiData.wikiPageUrl} />
        </>: []}
        {githubWikiData?.filter(([,wikiData])=>wikiData.notesMD).map(([sourceIdentifier, wikiData]) =>
            <Fragment key={sourceIdentifier}>
                <h3>GitHub Wiki notes (<SourceName source={evt.game.scriptSources[sourceIdentifier]!} />)</h3>
                <WikiMarkdown data-analytics-id="docs-caveats-githubwiki" gameData={evt.game} md={wikiData.notesMD!} baseURL={wikiData.linkToWikiData} />
            </Fragment>
        )}
    </GuardEmptyList>;
}

function Parameters({evt, ckWikiDataPromise, githubWikiDataPromise}: {readonly evt: PapyrusScriptEventOrBaseFunctionIndexedAggregate<PapyrusGame>, readonly ckWikiDataPromise: ReturnType<typeof getMediaWikiEventData>, readonly githubWikiDataPromise: Promise<Awaited<ReturnType<typeof getGitHubWikiEventData>>>}) {
    const ckWikiData = use(ckWikiDataPromise);
    const githubWikiData = use(githubWikiDataPromise);

    // eslint-disable-next-line react/no-unstable-nested-components -- these components are server components, so we don't really care
    return <GuardEmptyList replacement={null} Wrapper={({children}) => <>
        <br />
        <h2>Parameters</h2>
        <div data-analytics-id="docs-parameters" className={styles.parameters}>
            {children}
        </div>
    </>}>
        {evt.parameters.map((param, index) => {
            const lowercaseParamName = toLowerCase(param.name);
            const ckWikiParamData = ckWikiData?.parameters[index];

            const githubWikiParamDatas = githubWikiData?.map(([sourceIdentifier, wikiData]) => {
                const firstPass = wikiData.parameters[lowercaseParamName];
                if (firstPass) return [sourceIdentifier, firstPass] as const;

                if (lowercaseParamName.startsWith('a_')) { // Some sources prefix all of their parameters with 'a_', but don't do so in the wiki
                    const withoutPrefix = lowercaseParamName.slice(2) as Lowercase<string>;
                    const secondPass = wikiData.parameters[withoutPrefix];
                    if (secondPass) return [sourceIdentifier, secondPass] as const;
                }

                return null;
            }).filter((v): v is NonNullable<typeof v> => v !== null) ?? [];

            return <div key={param.name}>
                <h3>
                    {param.isRequired
                        ? <PapyrusTypeNamed game={evt.game.game} name={param.name} type={param.value} />
                        : <PapyrusTypeWithValue game={evt.game.game} type={param.value} name={param.name} />}
                </h3>
                {ckWikiParamData?.descriptionMarkdown ? <>
                    <h4>CK Wiki Description</h4>
                    <WikiMarkdown data-analytics-id="docs-parameter-description-ckwiki" gameData={evt.game} md={ckWikiParamData.descriptionMarkdown} baseURL={ckWikiData!.wikiPageUrl} />
                </> : null}
                {githubWikiParamDatas.filter(([,wikiData]) => wikiData.descriptionMD).map(([sourceIdentifier, paramWikiData]) =>
                    <Fragment key={sourceIdentifier}>
                        <h4>GitHub Wiki Description (<SourceName source={evt.game.scriptSources[sourceIdentifier]!} />)</h4>
                        <WikiMarkdown data-analytics-id="docs-parameter-description-githubwiki" gameData={evt.game}
                            md={paramWikiData.descriptionMD!} baseURL={paramWikiData.linkToWikiData} />
                    </Fragment>
                )}
            </div>;
        })}
    </GuardEmptyList>;
}

function RelatedPages({gameData, ckWikiDataPromise, githubWikiDataPromise}: {readonly gameData: PapyrusGameDataIndexed<PapyrusGame>, readonly ckWikiDataPromise: ReturnType<typeof getMediaWikiEventData>, readonly githubWikiDataPromise: Promise<Awaited<ReturnType<typeof getGitHubWikiEventData>>>}) {
    const ckWikiData = use(ckWikiDataPromise);
    const githubWikiData = use(githubWikiDataPromise);

    let seeAlsoMd = ckWikiData?.seeAlsoMarkdown ?? '';

    const dedupedLinks = new Set<string>();
    for (const [, wikiData] of githubWikiData) {
        for (const link of wikiData.seeAlso) {
            if (dedupedLinks.has(link.uri)) continue;
            seeAlsoMd += `\n- [${link.name}](${link.uri})\n`;
            dedupedLinks.add(link.uri);
        }
    }

    // eslint-disable-next-line react/no-unstable-nested-components -- these components are server components, so we don't really care
    return <GuardEmptyList replacement={null} Wrapper={({children}) => <>
        <br />
        <div data-analytics-id="docs-related">
            <h2>Related Pages</h2>
            {children}
        </div>
    </>}>
        {seeAlsoMd.length === 0 ? [] : <WikiMarkdown gameData={gameData} md={seeAlsoMd} baseURL={ckWikiData?.wikiPageUrl ?? AUTOMATIC_BASE_URL} />}
    </GuardEmptyList>;
}

function AdditionalReferences({game, ckWikiDataPromise, githubWikiDataPromise}: {readonly game: PapyrusGame, readonly ckWikiDataPromise: ReturnType<typeof getMediaWikiEventData>, readonly githubWikiDataPromise:Promise<Awaited<ReturnType<typeof getGitHubWikiEventData>>>}) {
    const ckWikiData = use(ckWikiDataPromise);
    const githubWikiData = use(githubWikiDataPromise);

    // eslint-disable-next-line react/no-unstable-nested-components -- these components are server components, so we don't really care
    return <GuardEmptyList replacement={null} Wrapper={({children}) => <>
        <br />
        <div data-analytics-id="docs-additional-references">
            <h2>Additional References</h2>
            {children}
        </div>
    </>}>
        {...[
            ckWikiData?.wikiPageUrl && <p key="ck-wiki-link"><a href={ckWikiData.wikiPageUrl} target="_blank" rel="noopener noreferrer">View this event&rsquo;s page on the {ckWikiData.wikiName}</a></p>,
            ...githubWikiData.map(([sourceIdentifier, wikiData]) =>
                <p key={wikiData.linkToWikiData}>
                    <a href={wikiData.linkToWikiData} target="_blank" rel="noopener noreferrer">View this event on the GitHub Wiki for <SourceName long source={AllScriptsIndexed[game].scriptSources[sourceIdentifier]!} /></a>
                </p>
            )
        ].filter(Boolean)}
    </GuardEmptyList>;

}

function RegistrationFunctions({evt, githubWikiDataPromise}: {readonly evt: PapyrusScriptEventOrBaseFunctionIndexedAggregate<PapyrusGame>, readonly githubWikiDataPromise: Promise<Awaited<ReturnType<typeof getGitHubWikiEventData>>>}) {
    const githubWikiData = use(githubWikiDataPromise);

    const knownRegistrationFunctions = Array.from(
        githubWikiData.flatMap(([, wikiData]) => wikiData.registrationControlFunctions).filter((f):f is Exclude<typeof f, null> => f !== null)
    );

    // TODO: Add "guessed" registration functions

    const registrationFunctions = Array.from(new Map<string, {name: string, func: PapyrusScriptFunctionIndexedAggregate<PapyrusGame> | undefined}>(
        knownRegistrationFunctions.map((funcName) => [funcName, {name: funcName, func: evt.script.functions[funcName]}])
    ));

    if (registrationFunctions.length === 0) return null;

    return <div data-analytics-id="docs-registration-functions">
        <h2>Registration Control Functions</h2>
        <ul>
            {registrationFunctions.map(([funcName, {name, func}]) => {
                if (func) {
                    return <li key={funcName}>
                        <PapyrusScriptFunctionReference game={evt.game.game} funcAggregate={func} scriptAggregate={evt.script} />
                    </li>;
                } else {
                    return <li key={funcName}>
                        <NotFoundChip /> {name}
                    </li>;
                }
            })}
        </ul>
    </div>;
}