import type { Metadata } from "next";
import { Fragment, use } from "react";
import type { PapyrusScriptFunctionIndexedAggregate } from "../../../../../../../papyrus/data-structures/indexing/function";
import { AllSourcesCombined, type PapyrusGameDataIndexed } from "../../../../../../../papyrus/data-structures/indexing/game";
import type { PapyrusGame } from "../../../../../../../papyrus/data-structures/pure/game";
import { AllScriptsIndexed } from "../../../../../../../papyrus/indexing/index-all";
import { getBestStringVariant } from "../../../../../../../utils/getBestName";
import { getGameName } from "../../../../../../../utils/getGameName";
import { toLowerCase } from "../../../../../../../utils/toLowerCase";
import { getMediaWikiFunctionData } from "../../../../../../../wiki-data-extraction/ck-wiki/data-extraction/getMediaWikiFunctionData";
import { CodeBlock, CodeBlockLanguage } from "../../../../../../components/code-block/CodeBlock";
import { GuardEmptyList } from "../../../../../../components/GuardEmptyList";
import { AutoGeneratedFunctionExampleText } from "../../../../../../components/papyrus/function/AutoGeneratedFunctionExampleText";
import { FunctionDocumentationStringRaw } from "../../../../../../components/papyrus/function/signature/DocumentationString";
import { PapyrusFunctionSignatureVariants } from "../../../../../../components/papyrus/function/signature/FunctionSignatureVariants";
import { getGitHubWikiFunctionData } from "../../../../../../components/papyrus/function/signature/getGitHubWikiFunctionDescription";
import { SourceName } from "../../../../../../components/papyrus/SourceName";
import { PapyrusTypeNamed, PapyrusTypeWithValue } from "../../../../../../components/papyrus/type/PapyrusType";
import { SuspenseIfDevelopment } from "../../../../../../components/SuspenseIfDevelopment";
import { TextWithTooltip } from "../../../../../../components/text-with-tooltip/TooltipText";
import { WikiMarkdown } from "../../../../../../components/wiki-markdown/WikiMarkdown";
import { getGameAndScriptAndFunctionFromParams, type FunctionRouteParams } from "./getGameAndScriptAndFunctionFromParams";
import styles from './FunctionPage.module.scss';

export function generateStaticParams(): FunctionRouteParams[] {
    const params: FunctionRouteParams[] = [];
    for (const [game, gameData] of Object.entries(AllScriptsIndexed)) {
        for (const [scriptNameLowercase, scriptData] of Object.entries(gameData.scripts)) {
            for (const funcName of Object.keys(scriptData[AllSourcesCombined].functions))
                params.push({game: toLowerCase(game), scriptNameNoExt: scriptNameLowercase, functionName: funcName});
        }
    }

    return params;
}

export async function generateMetadata({params}: {readonly params: Promise<FunctionRouteParams>}): Promise<Metadata> {
    const {game, scriptBySources, func} = getGameAndScriptAndFunctionFromParams(await params);

    const sourceIDs = Object.keys(scriptBySources);
    const sourceNames = sourceIDs.map((sourceId)=>SourceName({source: AllScriptsIndexed[game].scriptSources[sourceId]!, long: true}));

    if (sourceNames.length === 0) throw new Error('A script should have at least one source! Makes no sense for it to not have a source! Something is VERY wrong here.');
    const sourcesList = sourceNames.length === 1 ? sourceNames[0] : sourceNames.length === 2 ? sourceNames.join(' and ') : `${sourceNames.slice(0, -1).join(', ')}, and ${sourceNames.at(-1)}`;

    const scriptNamespaceName = getBestStringVariant(scriptBySources[AllSourcesCombined].namespaceName)![1];
    const description = await FunctionDocumentationStringRaw({game, func, scriptName: scriptNamespaceName});

    const functionName = getBestStringVariant(func.name)![1];

    return {
        title: functionName,
        description: `Reference page for the ${func.isGlobal.some(v=>v[1]) ? 'Global (static)' : 'Member'} function ${scriptNamespaceName}.${functionName} for the game ${getGameName(game)}. This script is provided by ${sourcesList}.${description ? `\n\n${description}` : ''}`,
        // TODO: Add keywords relevant to the function.
        // Possibly break its name down into parts, take its parameters into account, return type, parent script, and all that fun stuff.
    };
}

export default async function FunctionPage({params}: {readonly params: Promise<FunctionRouteParams>}) {
    const {game, scriptBySources, func} = getGameAndScriptAndFunctionFromParams(await params);

    const scriptNamespaceName = getBestStringVariant(scriptBySources[AllSourcesCombined].namespaceName)![1];

    const ckWikiDataPromise = getMediaWikiFunctionData(game, func, scriptNamespaceName);
    const githubWikiDataPromise = Promise.resolve(getGitHubWikiFunctionData(func));

    return <main>
        <GuardEmptyList replacement={<p>No variants of this function found.</p>}>
            <PapyrusFunctionSignatureVariants game={game} funcAggregate={func} scriptName={scriptNamespaceName} longerDescription />
        </GuardEmptyList>

        <SuspenseIfDevelopment fallback={<p>[Development] Loading caveats...</p>}>
            <Caveats
                func={func}
                ckWikiDataPromise={ckWikiDataPromise} githubWikiDataPromise={githubWikiDataPromise}
            />
        </SuspenseIfDevelopment>

        <SuspenseIfDevelopment fallback={<p>[Development] Loading parameters...</p>}>
            <Parameters
                func={func}
                ckWikiDataPromise={ckWikiDataPromise} githubWikiDataPromise={githubWikiDataPromise}
            />
        </SuspenseIfDevelopment>

        <SuspenseIfDevelopment fallback={<p>[Development] Loading examples...</p>}>
            <Examples
                func={func} scriptNamespaceName={scriptNamespaceName}
                ckWikiDataPromise={ckWikiDataPromise} githubWikiDataPromise={githubWikiDataPromise}
            />
        </SuspenseIfDevelopment>

        <SuspenseIfDevelopment fallback={<p>[Development] Loading related pages...</p>}>
            <RelatedPages
                gameData={func.game}
                ckWikiDataPromise={ckWikiDataPromise}
            />
        </SuspenseIfDevelopment>

        <SuspenseIfDevelopment fallback={<p>[Development] Loading wiki link...</p>}>
            <AdditionalReferences
                game={game}
                ckWikiDataPromise={ckWikiDataPromise} githubWikiDataPromise={githubWikiDataPromise}
            />
        </SuspenseIfDevelopment>
    </main>;
}

function Examples({func, ckWikiDataPromise, githubWikiDataPromise, scriptNamespaceName}: {readonly scriptNamespaceName: string, readonly func: PapyrusScriptFunctionIndexedAggregate<PapyrusGame>, readonly ckWikiDataPromise: ReturnType<typeof getMediaWikiFunctionData>, readonly githubWikiDataPromise: Promise<Awaited<ReturnType<typeof getGitHubWikiFunctionData>>>}) {
    const ckWikiData = use(ckWikiDataPromise);
    const githubWikiData = use(githubWikiDataPromise);
    return <>
        <br />
        <h2>Examples</h2>
        {/* eslint-disable-next-line react/jsx-no-bind, react/no-unstable-nested-components -- these components are server components, so we don't really care */}
        <GuardEmptyList replacement={<p>No human-generated examples found for this function.</p>} Wrapper={({children}) =>
            <div data-analytics-id="docs-examples">
                {children}
            </div>}
        >
            {ckWikiData?.examplesData.map((example) =>
                <div key={example.code}>
                    <CodeBlock language={CodeBlockLanguage.Papyrus} code={example.code} />
                </div>
            )}
            {githubWikiData?.filter(([,wikiData])=>wikiData.exampleMDs.length > 0).flatMap(([_sourceIdentifier, wikiData]) =>
                wikiData.exampleMDs.map((exampleMd) =>
                    <div key={exampleMd}>
                        <WikiMarkdown data-analytics-id="docs-examples-githubwiki" gameData={func.game}
                            md={exampleMd} baseURL={wikiData.linkToWikiData} />
                    </div>
                )
            )}
        </GuardEmptyList>

        <h3>
            <TextWithTooltip tooltipContents={<>
                <p>This example is auto-generated to show new Papyrus programmers roughly how to use this function.</p>
                <p>This example is NOT meant to be practical, nor is it meant to demonstrate anything more than the basic syntax of the function.</p>
            </>}>
                Auto-Generated Example
            </TextWithTooltip>
        </h3>
        <CodeBlock language={CodeBlockLanguage.Papyrus} code={AutoGeneratedFunctionExampleText({func: Object.values(func.$sources)[0]!, scriptName: scriptNamespaceName})} />
    </>;
}

function Caveats({func, ckWikiDataPromise, githubWikiDataPromise}: {readonly func: PapyrusScriptFunctionIndexedAggregate<PapyrusGame>, readonly ckWikiDataPromise: ReturnType<typeof getMediaWikiFunctionData>, readonly githubWikiDataPromise: Promise<Awaited<ReturnType<typeof getGitHubWikiFunctionData>>>}) {
    const ckWikiData = use(ckWikiDataPromise);
    const githubWikiData = use(githubWikiDataPromise);

    // eslint-disable-next-line react/jsx-no-bind, react/no-unstable-nested-components -- these components are server components, so we don't really care
    return <GuardEmptyList replacement={null} Wrapper={({children}) => <>
        <br />
        <div data-analytics-id="docs-caveats">
            <h2>Caveats</h2>
            {children}
        </div>
    </>}>
        {ckWikiData?.notesMarkdown ? <>
            <h3>CK Wiki - Notes</h3>
            <WikiMarkdown data-analytics-id="docs-notes-ckwiki" gameData={func.game} md={ckWikiData.notesMarkdown} baseURL={ckWikiData.wikiPageUrl} />
        </>: null}
        {ckWikiData?.bugsMarkdown ? <>
            <h3>CK Wiki - Known Bugs</h3>
            <WikiMarkdown data-analytics-id="docs-notes-ckwiki" gameData={func.game} md={ckWikiData.bugsMarkdown} baseURL={ckWikiData.wikiPageUrl} />
        </>: null}
        {githubWikiData?.filter(([,wikiData])=>wikiData.notesMD).map(([sourceIdentifier, wikiData]) =>
            <Fragment key={sourceIdentifier}>
                <h3>GitHub Wiki notes (<SourceName source={func.game.scriptSources[sourceIdentifier]!} />)</h3>
                <WikiMarkdown data-analytics-id="docs-caveats-githubwiki" gameData={func.game} md={wikiData.notesMD!} baseURL={wikiData.linkToWikiData} />
            </Fragment>
        )}
    </GuardEmptyList>;
}

function Parameters({func, ckWikiDataPromise, githubWikiDataPromise}: {readonly func: PapyrusScriptFunctionIndexedAggregate<PapyrusGame>, readonly ckWikiDataPromise: ReturnType<typeof getMediaWikiFunctionData>, readonly githubWikiDataPromise: Promise<Awaited<ReturnType<typeof getGitHubWikiFunctionData>>>}) {
    const ckWikiData = use(ckWikiDataPromise);
    const githubWikiData = use(githubWikiDataPromise);

    // eslint-disable-next-line react/jsx-no-bind, react/no-unstable-nested-components -- these components are server components, so we don't really care
    return <GuardEmptyList replacement={null} Wrapper={({children}) => <>
        <br />
        <h2>Parameters</h2>
        <div data-analytics-id="docs-parameters" className={styles.parameters}>
            {children}
        </div>
    </>}>
        {func.parameters.map((param, index) => {
            const lowercaseParamName = toLowerCase(param.name);
            const ckWikiParamData = ckWikiData?.parameters[index];

            const githubWikiParamDatas = githubWikiData?.map(([sourceIdentifier, wikiData]) => {
                const firstPass = wikiData.parameters[lowercaseParamName];
                if (firstPass) return [sourceIdentifier, firstPass] as const;

                if (lowercaseParamName.startsWith('a_')) { // Some sources prefix all of their parameters with 'a_', but don't do so in the wiki
                    const withoutPrefix = lowercaseParamName.slice(2) as Lowercase<string>;
                    const secondPass = wikiData.parameters[withoutPrefix];
                    if (secondPass) return [sourceIdentifier, secondPass] as const;
                }

                return null;
            }).filter((v): v is NonNullable<typeof v> => v !== null) ?? [];

            return <div key={param.name}>
                <h3>
                    {param.isRequired
                        ? <PapyrusTypeNamed game={func.game.game} name={param.name} type={param.value} />
                        : <PapyrusTypeWithValue game={func.game.game} type={param.value} name={param.name} />}
                </h3>
                {ckWikiParamData?.descriptionMarkdown ? <>
                    <h4>CK Wiki Description</h4>
                    <WikiMarkdown data-analytics-id="docs-parameter-description-ckwiki" gameData={func.game} md={ckWikiParamData.descriptionMarkdown} baseURL={ckWikiData!.wikiPageUrl} />
                </> : null}
                {githubWikiParamDatas.filter(([,wikiData]) => wikiData.descriptionMD).map(([sourceIdentifier, paramWikiData]) =>
                    <Fragment key={sourceIdentifier}>
                        <h4>GitHub Wiki Description (<SourceName source={func.game.scriptSources[sourceIdentifier]!} />)</h4>
                        <WikiMarkdown data-analytics-id="docs-parameter-description-githubwiki" gameData={func.game}
                            md={paramWikiData.descriptionMD!} baseURL={paramWikiData.linkToWikiData} />
                    </Fragment>
                )}
            </div>;
        })}
    </GuardEmptyList>;
}

function RelatedPages({gameData, ckWikiDataPromise}: {readonly gameData: PapyrusGameDataIndexed<PapyrusGame>, readonly ckWikiDataPromise: ReturnType<typeof getMediaWikiFunctionData>}) {
    const ckWikiData = use(ckWikiDataPromise);

    // eslint-disable-next-line react/jsx-no-bind, react/no-unstable-nested-components -- these components are server components, so we don't really care
    return <GuardEmptyList replacement={null} Wrapper={({children}) => <>
        <br />
        <div data-analytics-id="docs-related">
            <h2>Related Pages</h2>
            {children}
        </div>
    </>}>
        {ckWikiData?.seeAlsoMarkdown ? <WikiMarkdown gameData={gameData} md={ckWikiData.seeAlsoMarkdown} baseURL={ckWikiData.wikiPageUrl} /> : null}
    </GuardEmptyList>;
}

function AdditionalReferences({game, ckWikiDataPromise, githubWikiDataPromise}: {readonly game: PapyrusGame, readonly ckWikiDataPromise: ReturnType<typeof getMediaWikiFunctionData>, readonly githubWikiDataPromise:Promise<Awaited<ReturnType<typeof getGitHubWikiFunctionData>>>}) {
    const ckWikiData = use(ckWikiDataPromise);
    const githubWikiData = use(githubWikiDataPromise);

    // eslint-disable-next-line react/jsx-no-bind, react/no-unstable-nested-components -- these components are server components, so we don't really care
    return <GuardEmptyList replacement={null} Wrapper={({children}) => <>
        <br />
        <div data-analytics-id="docs-additional-references">
            <h2>Additional References</h2>
            {children}
        </div>
    </>}>
        {...[
            ckWikiData?.wikiPageUrl && <p key="ck-wiki-link"><a href={ckWikiData.wikiPageUrl} target="_blank" rel="noopener noreferrer">View this function&rsquo;s page on the {ckWikiData.wikiName}</a></p>,
            ...githubWikiData.map(([sourceIdentifier, wikiData]) =>
                <p key={wikiData.linkToWikiData}>
                    <a href={wikiData.linkToWikiData} target="_blank" rel="noopener noreferrer">View this function on the GitHub Wiki for <SourceName long source={AllScriptsIndexed[game].scriptSources[sourceIdentifier]!} /></a>
                </p>
            )
        ].filter(Boolean)}
    </GuardEmptyList>;

}
