import type { Metadata } from "next";
import { Suspense, use } from "react";
import { AllSourcesCombined, type PapyrusGameDataIndexed } from "../../../../../../../papyrus/data-structures/indexing/game";
import { AllScriptsIndexed } from "../../../../../../../papyrus/indexing/index-all";
import { getBestStringVariant } from "../../../../../../../utils/getBestName";
import { getGameName } from "../../../../../../../utils/getGameName";
import { toLowerCase } from "../../../../../../../utils/toLowerCase";
import { getMediaWikiFunctionData } from "../../../../../../../wiki-data-extraction/ck-wiki/data-extraction/getMediaWikiFunctionData";
import { CodeBlock, CodeBlockLanguage } from "../../../../../../components/code-block/CodeBlock";
import { GuardEmptyList } from "../../../../../../components/GuardEmptyList";
import { AutoGeneratedFunctionExampleText } from "../../../../../../components/papyrus/function/AutoGeneratedFunctionExampleText";
import { FunctionDocumentationStringRaw } from "../../../../../../components/papyrus/function/signature/DocumentationString";
import { PapyrusFunctionSignatureVariants } from "../../../../../../components/papyrus/function/signature/FunctionSignatureVariants";
import { SourceName } from "../../../../../../components/papyrus/SourceName";
import { TextWithTooltip } from "../../../../../../components/text-with-tooltip/TooltipText";
import { getGameAndScriptAndFunctionFromParams, type FunctionRouteParams } from "./getGameAndScriptAndFunctionFromParams";
import { WikiMarkdown } from "../../../../../../components/wiki-markdown/WikiMarkdown";
import { getGitHubWikiFunctionData } from "../../../../../../components/papyrus/function/signature/getGitHubWikiFunctionDescription";
import type { PapyrusGame } from "../../../../../../../papyrus/data-structures/pure/game";

export function generateStaticParams(): FunctionRouteParams[] {
    const params: FunctionRouteParams[] = [];
    for (const [game, gameData] of Object.entries(AllScriptsIndexed)) {
        for (const [scriptNameLowercase, scriptData] of Object.entries(gameData.scripts)) {
            for (const funcName of Object.keys(scriptData[AllSourcesCombined].functions))
                params.push({game: toLowerCase(game), scriptNameNoExt: scriptNameLowercase, functionName: funcName});
        }
    }

    return params;
}

export async function generateMetadata({params}: {readonly params: Promise<FunctionRouteParams>}): Promise<Metadata> {
    const {game, scriptBySources, func} = getGameAndScriptAndFunctionFromParams(await params);

    const sourceIDs = Object.keys(scriptBySources);
    const sourceNames = sourceIDs.map((sourceId)=>SourceName({source: AllScriptsIndexed[game].scriptSources[sourceId]!, long: true}));

    if (sourceNames.length === 0) throw new Error('A script should have at least one source! Makes no sense for it to not have a source! Something is VERY wrong here.');
    const sourcesList = sourceNames.length === 1 ? sourceNames[0] : sourceNames.length === 2 ? sourceNames.join(' and ') : `${sourceNames.slice(0, -1).join(', ')}, and ${sourceNames.at(-1)}`;

    const scriptNamespaceName = getBestStringVariant(scriptBySources[AllSourcesCombined].namespaceName)![1];
    const description = await FunctionDocumentationStringRaw({game, func, scriptName: scriptNamespaceName});
    return {
        title: getBestStringVariant(func.name)![1],
        description: `Reference page for the ${func.isGlobal.some(v=>v[1]) ? 'Global (static)' : 'Member'} function ${scriptNamespaceName}.${getBestStringVariant(func.name)![1]} for the game ${getGameName(game)}. This script is provided by ${sourcesList}.${description ? `\n\n${description}` : ''}`,
        // TODO: Add keywords relevant to the function.
        // Possibly break its name down into parts, take its parameters into account, return type, parent script, and all that fun stuff.
    };
}

export default async function FunctionPage({params}: {readonly params: Promise<FunctionRouteParams>}) {
    const {game, scriptBySources, func} = getGameAndScriptAndFunctionFromParams(await params);

    const scriptNamespaceName = getBestStringVariant(scriptBySources[AllSourcesCombined].namespaceName)![1];

    const ckWikiDataPromise = getMediaWikiFunctionData(game, func, scriptNamespaceName);
    const githubWikiDataPromise = Promise.resolve(getGitHubWikiFunctionData(func));

    return <main>
        <GuardEmptyList replacement={<p>No variants of this function found.</p>}>
            <PapyrusFunctionSignatureVariants game={game} funcAggregate={func} scriptName={scriptNamespaceName} longerDescription />
        </GuardEmptyList>

        <br />

        <h2>Examples</h2>
        <Suspense fallback={<p>[Development] Loading examples...</p>}>
            {ckWikiDataPromise.then(wikiData =>
                <GuardEmptyList replacement={<p>No human-generated examples found for this function.</p>}>
                    {wikiData?.examplesData.map((example)=><div key={example.code}>
                        <CodeBlock language={CodeBlockLanguage.Papyrus} code={example.code} />
                    </div>)}
                </GuardEmptyList>
            )}
        </Suspense>
        <h3>
            <TextWithTooltip tooltipContents={<>
                <p>This example is auto-generated to show new Papyrus programmers roughly how to use this function.</p>
                <p>This example is NOT meant to be practical, nor is it meant to demonstrate anything more than the basic syntax of the function.</p>
            </>}>
                Auto-Generated Example
            </TextWithTooltip>
        </h3>
        <CodeBlock language={CodeBlockLanguage.Papyrus} code={AutoGeneratedFunctionExampleText({func: Object.values(func.$sources)[0]!, scriptName: scriptNamespaceName})} />

        <br />

        <Suspense fallback={<p>[Development] Loading related pages...</p>}>
            <RelatedPages gameData={func.game} ckWikiDataPromise={ckWikiDataPromise} />
        </Suspense>

        <br />

        <Suspense fallback={<p>[Development] Loading wiki link...</p>}>
            <AdditionalReferences
                game={game}
                ckWikiDataPromise={ckWikiDataPromise}
                githubWikiDataPromise={githubWikiDataPromise}
            />
        </Suspense>
    </main>;
}

function RelatedPages({gameData, ckWikiDataPromise}: {readonly gameData: PapyrusGameDataIndexed<PapyrusGame>, readonly ckWikiDataPromise: ReturnType<typeof getMediaWikiFunctionData>}) {
    const ckWikiData = use(ckWikiDataPromise);

    // eslint-disable-next-line react/jsx-no-bind, react/no-unstable-nested-components -- these components are server components, so we don't really care
    return <GuardEmptyList replacement={null} Wrapper={({children}) =>
        <div data-analytics-id="docs-related">
            <h2>Related Pages</h2>
            {children}
        </div>}
    >
        {ckWikiData?.seeAlsoMarkdown ? <WikiMarkdown gameData={gameData} md={ckWikiData.seeAlsoMarkdown} baseURL={ckWikiData.wikiPageUrl} /> : []}
    </GuardEmptyList>;
}

function AdditionalReferences({game, ckWikiDataPromise, githubWikiDataPromise}: {readonly game: PapyrusGame, readonly ckWikiDataPromise: ReturnType<typeof getMediaWikiFunctionData>, readonly githubWikiDataPromise:Promise<Awaited<ReturnType<typeof getGitHubWikiFunctionData>>>}) {
    const ckWikiData = use(ckWikiDataPromise);
    const githubWikiData = use(githubWikiDataPromise);

    // eslint-disable-next-line react/jsx-no-bind, react/no-unstable-nested-components -- these components are server components, so we don't really care
    return <GuardEmptyList replacement={null} Wrapper={({children}) =>
        <div data-analytics-id="docs-additional-references">
            <h2>Additional References</h2>
            {children}
        </div>}
    >
        {...[
            ckWikiData?.wikiPageUrl && <p key="ck-wiki-link"><a href={ckWikiData.wikiPageUrl} target="_blank" rel="noopener noreferrer">View this function&rsquo;s page on the {ckWikiData.wikiName}</a></p>,
            ...githubWikiData.map(([sourceIdentifier, wikiData]) =>
                <p key={wikiData.linkToWikiData}>
                    <a href={wikiData.linkToWikiData} target="_blank" rel="noopener noreferrer">View this function on the GitHub Wiki for <SourceName long source={AllScriptsIndexed[game].scriptSources[sourceIdentifier]!} /></a>
                </p>
            )
        ].filter(Boolean)}
    </GuardEmptyList>;

}
