import type { PapyrusScriptEventOrBaseFunctionIndexed, PapyrusScriptFunctionIndexed } from "../../../../papyrus/data-structures/indexing/function";
import type { PapyrusGame } from "../../../../papyrus/data-structures/pure/game";
import { papyrusTypeToString } from "../type/PapyrusType";

export function AutoGeneratedEventExampleText<TGame extends PapyrusGame>({evt, scriptName, registrationControls}: {readonly evt: PapyrusScriptEventOrBaseFunctionIndexed<TGame>, readonly scriptName: string, registrationControls: null | {
    unregister: PapyrusScriptFunctionIndexed<TGame> | null,
    unregisterAll: PapyrusScriptFunctionIndexed<TGame> | null,
    register: PapyrusScriptFunctionIndexed<TGame>,
}}): string {

    let debugTraceLine = `Debug.trace("Event received - ${evt.name}`;
    if (evt.parameters.length === 0) debugTraceLine += `")`;
    else debugTraceLine += `: ${evt.parameters.map(p => `${p.name} = " + ${p.name}`).join(' + " ')})`;

    const registration = registrationControls === null ? '' : (()=>{
        const parameterData = registrationControls.register.parameters.filter(p => p.isRequired).map(p => {
            const typeName = papyrusTypeToString(p.value);
            const typeNameForVarName = (typeName.charAt(0).toUpperCase() + typeName.slice(1, -2) + (typeName.endsWith('[]') ? 'Array' : typeName.slice(-2))).replaceAll(':', '_');
            return [typeName, `my${typeNameForVarName}__${p.name}`] as const;
        });

    return `
event OnInit()
    ${registrationControls.register.isGlobal ? scriptName : 'this'}.${registrationControls.register.name}(${parameterData.map(([, varName]) => varName).join(', ')})
endEvent
`.trim();
})();

    return `
Scriptname MyCoolScript extends ${scriptName}

event ${evt.name}(${evt.parameters.map(p => papyrusTypeToString(p.value) + ' ' + p.name).join(', ')   /* eslint-disable-line prefer-template */})
    ${debugTraceLine}
endEvent

${registration}

`.trim();

}
